SELECT 
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * -3, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * -3, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * -3, 0),CURRENT_TIMESTAMP)))
, 110) as year_3,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * -2, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * -2, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * -2, 0),CURRENT_TIMESTAMP)))
, 110) as year_2,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * -1, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * -1, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * -1, 0),CURRENT_TIMESTAMP)))
, 110) as year_1,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * 0, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * 0, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * 0, 0),CURRENT_TIMESTAMP)))
, 110) as year0,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * 1, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * 1, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * 1, 0),CURRENT_TIMESTAMP)))
, 110) as year1,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * 2, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * 2, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * 2, 0),CURRENT_TIMESTAMP)))
, 110) as year2,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * 3, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * 3, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * 3, 0),CURRENT_TIMESTAMP)))
, 110) as year3,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * 4, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * 4, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * 4, 0),CURRENT_TIMESTAMP)))
, 110) as year4,
CONVERT(varchar(10),
CONVERT(varchar(4),DATEPART(yy, DATEADD(week, ROUND(52.1775 * 5, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(mm, DATEADD(week, ROUND(52.1775 * 5, 0),CURRENT_TIMESTAMP))) + '-' + 
CONVERT(varchar(2),DATEPART(dd, DATEADD(week, ROUND(52.1775 * 5, 0),CURRENT_TIMESTAMP)))
, 110) as year5